### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by matze19999** [Steiger04/ioBroker.radar-trap#1]
From which source are the radars?

I couldn't find it in the code

Thank you!

**Comment by Steiger04** [comment]
Ich bin mir nicht sicher was genau Du wissen willst. Falls Du die atudo-Abfrage meinst, die findest Du **[hier](https://github.com/Steiger04/ioBroker.radar-trap/blob/main/src/lib/atudo/traps.ts)**.

**Comment by matze19999** [comment]
> Ich bin mir nicht sicher was genau Du wissen willst. Falls Du die atudo-Abfrage meinst, die findest Du **[hier](https://github.com/Steiger04/ioBroker.radar-trap/blob/main/src/lib/atudo/traps.ts)**.

Genau die meinte ich, vielen Dank!
