### ISSUE TITLE
URGENT - Please fix io-package.jsons ASAP

### ISSUE THREAD

**Issue by mcm1957** [Steiger04/ioBroker.radar-trap#12]
**Current io-package.json is no valid json file. Please fix ASAP as the broke file blocks checks for central repositories and might cause the repobuild job to fail.**

Besides your last commit reverted several changes to io-packeg.json (license, installedFrom rreappered) etc. Please fix / revert.

Please note that I might need to remove the adpter from repositories if io-package.json is not fixed as soon as possible.

Thanks

**Comment by Steiger04** [comment]
@mcm1957 Ich hatte ein Problem mit git / GitHub, wodurch meine io-package.json auf einen alten Stand "aktualisiert" wurde. Problem habe ich aber sofort nochdem es mir aufgefallen ist wieder gefixt, d.h. in der aktuellen v2.2.1 und auch davor ist alles ok.

**Comment by mcm1957** [comment]
Danke für den schnellen Fix
