### ISSUE TITLE
Log Eintrag  Method "createState" is deprecated 

### ISSUE THREAD

**Issue by Horgul123** [Steiger04/ioBroker.radar-trap#13]
Im Log kommt folgender Eintrag:
`
radar-trap.0 | 2024-07-27 08:00:20.491 | info | Method "createState" is deprecated and will be removed in js-controller 7, use "extendObject/setObjectNotExists" instead
`

Adapter Version 2.2.1
js-controller 6.0.9
node-js 20.15.1

Bitte mal prüfen :)

**Comment by Steiger04** [comment]
Das ist nur der Hinweis, dass ab v7.x.y des js-controller der Adapter angepasst werden muss. Bis dahin läuft alles wie es soll. v7 ist noch ganz weit weg.
