### ISSUE TITLE
Check restart and visWidget section at io-package.json

### ISSUE THREAD

**Issue by mcm1957** [Steiger04/ioBroker.radar-trap#7]
As you support vis-2 now, a restart vis-2 seems to be appropiate. Maybe the restart vis should be kept to ensure that vis(1) is restarted after upgradung this adapter to 2.x.x and hence to remove vis(1) widgets form vis(1).

```
    "restartAdapters": [
      "vis"0
    ],
```

In addition the visWidget section should be checked. According to README only vis-2 is supported, but the section tells that major version 2 is not supported (while this indiocates that version 1 is supported)

```
    "visWidgets": {
      "ignoreInVersions": [
        2
      ]
    },
```

**Comment by Steiger04** [comment]
@mcm1957 Bei `ignoreInVersions` machst Du einen Denkfehler. Wenn Du Dir den Code in vis-2 anschaust: 

```
async function readAdapterList() {
    const res = await adapter.getObjectViewAsync('system', 'instance', {});

    const instances = [];
    res.rows
        .forEach(item => {
            const obj = item.value;
            // ignore widgets for V1 only
            if (obj?.common?.visWidgets?.ignoreInVersions?.includes(2)) {
                return;
            }
            const name = obj && obj._id && obj._id.replace('system.adapter.', '').replace(/\.\d+$/, '');
            if (name && !instances.includes(name)) {
                instances.push(name);
            }
        });

    instances.sort();

    let sets = [];
    POSSIBLE_WIDGET_SETS_LOCATIONS.forEach(dir => collectWidgetSets(dir, sets));
    sets = sets.filter(s => instances.includes(s.name.substring('iobroker.'.length)));

    return sets;
}
```
Das bedeutet die vis-Widgets (im Ordner widgets) des Adapter radar-trap werden in vis-2 nicht berücksichtigt, da ja vis-Widgets und nicht vis-2 Widgets. Von daher macht:

```
"visWidgets": {
      "ignoreInVersions": [
        2
      ]
    }
```

eigentlich genau was es soll.

**Comment by mcm1957** [comment]
Ja "ignoreInVersions": [ 2 ] besagt, dass die widgets in vis-2  nicht berücksichtigt werden. ABER im changelog steht unter 2.0.0

_(Steiger04) !!! No VIS widgets anymore. Continue using v1.3.1 for VIS widgets. **Starting from this version, only VIS-2 widgets are supported. !!!**_

Das liest sich für mich so, als würde der Adapter ab 2.0.0 nur mehr vis 2 Widgets aber keine vis (vis 1 ) Widgets mehr ausliefern. Das ist ein Widerspruch zum ignoreInVersions. Daher habe ich auch gebeten das zu prüfen,

Nach deinem jetzigen Text ist es aber so, das das Adapter keine widgets mehr ausliefert (siehe .npmignore). Ist auch völlig OK, mich hat dann nur der changelog verwirrt. Ev. kann man da was klarstellen. Und eigentlich kann man dann die nicht mehr ausgeliferten Files auf Github auch löschen (in der History bleiben sie ja erhalten).

Da der Adapter nun gar keine Widgets (weder vis noch vis-2) ausliefert - wenn ichs endlich richtig kapiert habe - stellt sich die Frage ob ein Restart überhaupt notwendig ist oder die Restart Clause ganz aus io-package.json entfernt werden kann.

Ansonsten DANKE fürs Anschaun und Feedback. Mach hier zu wann immer du willst.
