### ISSUE TITLE
Can't create a route or anything

### ISSUE THREAD

**Issue by 9Mad-Max5** [Steiger04/ioBroker.radar-trap#9]
**Describe the bug**  
If I enter my token from Mapbox, it loads the world. If I then click on the tab routs, it is infinitely loading.
Without any result, even changing to debug mode, the adapter not outputs any information.
Tested in a docker environment, once inside a Debian distro, and once inside an LXC.

**To Reproduce**  
1. Install Adapter
2. Add default API Mapbox token
3. Click on routs "Routen"

**Expected behavior**  
Not sure how it should look, never used it before

**Screenshots & Logfiles**  
No logging as said but I later append a screenshot

**Versions:**  
 - Adapter version: v2.2.0
 - JS-Controller version: 5.0.19
 - Node version: v18.20.3
 - Operating system: docker (official image - v9.1.2)

**Additional context**  
There had been no objects created at all in the object structure seems to me ought.

**Comment by Steiger04** [comment]
Please create a new Mapbox API-Token and try it again.

**Comment by 9Mad-Max5** [comment]
Already made a secret one with all settings, same behavior.

**Comment by Steiger04** [comment]
Is there any error message in the browser developer console?

**Comment by 9Mad-Max5** [comment]
Oh that's a good point never considered that it needs to have external ports opened.
Just used traefik as a reverse proxy. If i connect localy it works perfectly.
Failed to load resource:
https://iobroker.xx:3040/socket.io/?EIO=3&transport=polling&t=P0xx

Why does it need to have an open port at this place?
Didn't take a close look at the architecture...
Or maybe a hint in the documentation would be nice.

**Comment by Steiger04** [comment]
Therefore I wrote a wiki on GitHub 😄.

**Comment by 9Mad-Max5** [comment]
Oh I see at the low end side but still I didn't consider how feathers is working or more precise it is using my incoming address to access feathers
